# [171008] Today I Learned

러닝스칼라공부시작

## Scala REPL :load, :paste

스칼라의 강점으로 REPL이 자주 언급된다. 인터프리터로 작성한 코드를 바로 실행할 수 있는 기능이지만, 여러줄의 코드를 실행하거나 할때에는 직접 타이핑하는데 꽤 오랜 시간이 걸린다.
그래서 REPL을 사용하지 않고 매번 IDE를 이용하여 데모프로젝트를 작성해 코드를 검증하는 편이다.

REPL이 가진 위의 불편함을 해결할 수 있는 방법을 러닝스칼라에서 알게 되어 공유한다.

* `:load <파일명>`을 이용하면 해당 파일을 읽어 파일을 로드할 수 있다.
+
----
scala> :load Hello.scala
Loading Hello.scala...
Hello, World!
----
+
* `:paste` 를 입력하면 멀티라인 문자열도 쉽게 작성할 수 있다.
+
----
scala> :paste
// Entering paste mode (ctrl-D to finish)

println("Hello, World!")


// Exiting paste mode, now interpreting.

Hello, World!
----

위 기능은 REPL에서만 동작하므로 일반적인 scala 코드를 작성할때는 동작하지 않으므로 유의하자. :)

## literal, value, variable, type

러닝스칼라 2장에서..

* **리터럴(literal)**은 숫자 5, 문자 A, 텍스트 'Hello, World!'처럼 소스코드에 바로 등장하는 데이터이다.
* **값(value)**는 불변의 타입을 갖는 저장단위다. 값은 정의될 때 데이터가 할당될 수 있지만, 절대 재할당될 수 없다.
* **변수(variable)**는 가변의 타입을 갖는 저장단위이다. 변수는 정의시 데이터를 할당할 수 있으며, 언제라도 데이터를 재할당할 수 있다.
* **타입(type)**은 여러분이 작업하는 데이터의 종류로, 데이터의 정의 또는 분류를 의미한다. 스칼라의 모든 데이터는 특정 타입에 대응하며, 모든 스칼라 타입은 그 데이터를 처리하는 메소드를 가지는 클래스로 정의된다.

## atom 단축키 추가하기

atom 에디터를 다용도로 사용하고 있다. 코드를 빠르게 볼때에도 사용하고 asciidoc을 작성하는 용도로도 사용한다. 문서도구로써 사용하기에는 soft-wrap이 되어있는 상태가 좋지만, 코드뷰어로써는 soft-wrap이 꺼진상태가 더 보기 편하다. 하지만 toggle soft wrap 기능에 별다른 단축키가 할당되어있지않아서 불편해서 단축키를 추가하는 방법을 찾게 되었다.

[preferences] - [keybindings] 로 접근해 설명글 하위의 `keymap file`을 클릭하면 `keymap.cson`파일을 열 수 있다. 아래에 다음과 같이 새로운 라인을 추가하여 단축키를 추가할 수 있다.

----
'body':
  'alt-cmd-\\': 'editor:toggle-soft-wrap'
----

딱히 괜찮은 asciidoc 에디터가 없기 때문에 지금과 같이 커스터마이징을 해나가는 중이다.
