= [171103] Today I Learned

== 401과 403의 차이

둘다 인증실패일때 반환되는 오류코드... 이 둘의 차이점이 뭔지를 조사해보았다.

* 401 : 사용자 인증과 관련된 코드. 401번 상태 코드가 전달되면 웹브라우저는 사용자에게 아이디와 패스워드를 입력할 것을 요구함. 여기서 제대로 된 아이디와 패스워드를 입력할 경우 해당 URL로 이동이 되고, 만일 실패 할 경우 403번 상태 코드를 발생시킴.
* 403 : 웹브라우저가 요청한 부분이 접근 권한이 없는 영역임. 웹에서 들어오는 사용자에게 파일에 대한 접근 권한을 막았거나, 401번 상태 코드 발생 후 제대로 된 아이디와 패스워드를 입력시키지 않았을 경우에 발생함.

== 스칼라 스터디 준비



=== 표현식과 문장

* 표현식(expression) : 값을 반환하는 코드의 단위
* 문장(statement) : 값을 반환하지 않는 표현식

괄호로 묶어 하나의 단일 표현식 블록을 만들 수 있다.

[source, scala]
----
scala> val amount = {
     | val x = 5 * 20
     | x + 10
     | }

amount: Int = 110
----

괄호로 묶인 영역 제일 마지막에 들어가는 `x + 10`이 이 표현식에서 반환되는 값이다.

전체로 보았을때 `val amount = <표현식>` 은 반환값이 없으므로 문장이라고 할 수 있을 것이다.

==== if-else 표현식

다른 언어와 다르게 if 는 값을 반환하는 **표현식**이다. if의 조건문이 성립하는 경우 해당 표현식 결과가, 성립하지 않는 경우 else 표현식의 결과가 반환된다.

[source, scala]
----
scala> val x=10; val y=20
x: Int = 10
y: Int = 20

scala> val max = if (x > y) x else y;
max: Int = 20
----

==== match 표현식

match 표현식은 입력항목을 평가하여 처음으로 일치하는 패턴이 실행되고 그 결과값이 반환된다. C와 Java의 switch문과 유사하지만 타입에 따른 매칭이나 조건문을 결합하여 쓸 수 있는 등 switch와 다르게 훨씬 풍성하게 사용할 수 있다.

[source, scala]
----
scala> val input = 1
input: Int = 1

scala> val result = input match {
     |   case 1 => "one"
     |   case 2 => "two"
     |   case _:Int => "many"
     | }
result: String = one

----

case문에 변수로 시작하는 경우 매칭되는 표현식에서 해당 변수를 사용할 수 있습니다.
`_`는 변수로써는 사용 불가능하다.

[source, scala]
----
scala> val input:Any = 12180
input: Any = 12180

scala> input match {
     |   case x : String => s"'x'"
     |   case x : Int => s"${x}i"
     | }
res1: String = 12180i
----


여러개의 조건은 `|`를 이용하여 설정할 수 있다.

[source, scala]
----
scala> val day = "MON"
day: String = MON

scala> val kind = day match {
     |   case "SAT" | "SUN" => "weekend"
     |   case _ => "weekday"
     | }
kind: String = weekday
----

==== 패턴가드 사용하기

match 표현식에 if를 함께 사용하여 조건에 따른 분기처리가 가능하도록 할 수 있다.

[source, scala]
----
scala> val res = null
res: Null = null

scala> res match {
     |   case s if s!=null => println(s)
     |   case s => println("res is null")
     | }
res is null
----

==== 루프

스칼라는 for 구문, while 구문, do-while 구문을 지원한다. for문을 주로 사용하게 된다. while, do-while은 결과를 리턴하지 않기 때문에 잘 사용하지 않는다.

==== for 표현식

범위를 지정해주는 구문은 다음과 같다.
`<시작 정수값> [to|until] <끝 정수값> [by increment]`

for구문은 다음과 같다.
`for (<식별자> <- <반복자>) yield [<표현식>]`

[source, scala]
----
scala> for (a <- 1 to 3) {println(a)}
1
2
3
----

키워드 yield를 이용하는 경우 for의 결과값을 컬렉션으로 반환할 수 있다.

[source, scala]
----
scala> for (a <- 1 to 3) yield a
res9: scala.collection.immutable.IndexedSeq[Int] = Vector(1, 2, 3)
----

==== 값 바인딩

`for(<식별자> <- <반복자>; <식별자> = <표현식>)`
[source, scala]
----
for (x<-1 to 3; pow = x * x) yield pow
res1: scala.collection.immutable.IndexedSeq[Int] = Vector(1, 4, 9)
----



=== 함수

반복 사용할 수 있는 `표현식`을 정의하는 방법

`def <식별자>(<매개변수들>)[: <타입>] = <표현식>`

이렇게 정의된 함수는 아래와 같이 호출가능

`<식별자>(<매개변수들>)`

[source, scala]
----
scala> def add(x:Int, y:Int):Int = x + y
add: (x: Int, y: Int)Int

scala> add(1, 3)
res12: Int = 4
----

매개변수이름을 지정하여 함수를 호출할 수 있다.

[source, scala]
----
scala> add(y=5, x=4)
res12: Int = 9
----

매개변수는 기본값을 가질 수 있다.

[source, scala]
----
scala> def add(x:Int = 3, y:Int):Int = x + y
add: (x: Int, y: Int)Int

scala> add(y=2)
res14: Int = 5
----

연습문제

한쌍의 2차원점(x,y) 사이의 거리를 계산하는 함수를 작성하라

[source, scala]
----
def dist(x:(Int, Int), y:(Int, Int)):Double = {
  val yd = y._1 - y._2
  val xd = x._1 - y._2
  math.sqrt(yd * yd + xd * xd)
}
----

자바 루프 for (int i = 10; i >= 0; i++) System.out.println(i); 와 동일한
스칼라 코드를 작성하라.
