== 스칼라 스터디 준비

=== 표현식과 문장

* 표현식(expression) : 값을 반환하는 코드의 단위
* 문장(statement) : 값을 반환하지 않는 표현식

표현식 또는 문장은 괄호로 묶어 하나의 단일 블록으로 만들어낼 수 있다.

[source, scala]
----
val amount = {
  val x = 5 * 20
  x + 10
}

// amount: Int = 110
----

괄호로 묶인 영역 제일 마지막에 들어가는 `x + 10`이 이 표현식에서 반환되는 값이다.

전체로 보았을때 `val amount = <표현식>` 은 반환값이 없으므로 문장이라고 할 수 있을 것이다.

==== if-else 표현식

다른 언어와 다르게 if 는 값을 반환하는 **표현식**이다. if의 조건문이 성립하는 경우 해당 표현식 결과가, 성립하지 않는 경우 else 표현식의 결과가 반환된다.

[source, scala]
----
val x=10; val y=20
// x: Int = 10
// y: Int = 20

val max = if (x > y) x else y;
// max: Int = 20
----

==== match 표현식

match 표현식은 입력항목을 평가하여 처음으로 일치하는 패턴이 실행되고 그 결과값이 반환된다. C와 Java의 switch문과 유사하지만 타입에 따른 매칭이나 조건문을 결합하여 쓸 수 있는 등 switch와 다르게 훨씬 풍성하게 사용할 수 있다.

[source, scala]
----
val input = 1
// input: Int = 1

val result = input match {
  case 1 => "one"
  case 2 => "two"
  case _:Int => "many"
}

// result: String = one
----

case문에 변수로 시작하는 경우 매칭되는 표현식에서 해당 변수를 사용할 수 있다. `_`는 변수로써는 사용 불가능하다.

[source, scala]
----
val input:Any = 12180
// input: Any = 12180

input match {
  case x : String => s"'x'"
  case x : Int => s"${x}i"
}

// res1: String = 12180i
----


여러개의 조건은 `|`를 이용하여 설정할 수 있다.

[source, scala]
----
val day = "MON"
day: String = MON

val kind = day match {
  case "SAT" | "SUN" => "weekend"
  case _ => "weekday"
}

// kind: String = weekday
----

==== 패턴가드 사용하기

match 표현식에 if를 함께 사용하여 조건에 따른 분기처리가 가능하도록 할 수 있다.

[source, scala]
----
val res = null
// res: Null = null

res match {
  case s if s!=null => println(s)
  case s => println("res is null")
}

// res is null
----

==== 루프

스칼라는 for 구문, while 구문, do-while 구문을 지원한다.while, do-while은 문장으로 결과를 리턴하지 않기 때문에 사용빈도가 떨어지는 편이다.

==== for 문

범위를 지정해주는 구문은 다음과 같다.
`<시작 정수값> [to|until] <끝 정수값> [by increment]`

for구문은 다음과 같다.
`for (<식별자> <- <반복자>) yield [<표현식>]`

[source, scala]
----
for (a <- 1 to 3) {println(a)}

// 1
// 2
// 3
----

키워드 yield를 이용하는 경우 for의 결과값을 컬렉션으로 반환할 수 있다.

[source, scala]
----
for (a <- 1 to 3) yield a

// scala.collection.immutable.IndexedSeq[Int] = Vector(1, 2, 3)
----

==== 값 바인딩

`for(<식별자> <- <반복자>; <식별자> = <표현식>)`
[source, scala]
----
for (x<-1 to 3; pow = x * x) yield pow

// scala.collection.immutable.IndexedSeq[Int] = Vector(1, 4, 9)
----

=== 함수

반복 사용할 수 있는 `표현식`을 정의하는 방법

`def <식별자>(<매개변수들>)[: <타입>] = <표현식>`

이렇게 정의된 함수는 아래와 같이 호출가능

`<식별자>(<매개변수들>)`

[source, scala]
----
def add(x:Int, y:Int):Int = x + y
add: (x: Int, y: Int)Int

add(1, 3)
// Int = 4
----

함수를 호출하는 경우 매개변수이름을 지정하여 변수를 지정할 수 있다.

[source, scala]
----
add(y=5, x=4)
// Int = 9
----

매개변수는 기본값을 가질 수 있다.

[source, scala]
----
def add(x:Int = 3, y:Int):Int = x + y
// add: (x: Int, y: Int)Int

add(y=2)
// Int = 5
----

특정 정수의 n승의 결과를 구하는 재귀함수는 다음과 같이 구현할 수 있다.

[source, scala]
----
def pow(x: Int, n: Int): Int = {
    if (n >= 1) x * pow(x, n - 1)
    else 1
  }
pow: (x: Int, n: Int)Int

pow(2, 8)
// Int = 256
----

꼬리재귀는 다음과 같이 어노테이션을 붙여 선언이 가능하다.
[source, scala]
----
@annotation.tailrec
def pow(x: Int, n: Int, t: Int = 1): Int = {
  if (n < 1) t
  else pow(x, n - 1, t * x)
}
// pow: (x: Int, n: Int, t: Int)Int

pow(2, 8)
// Int = 256
----



==== 연습문제

한쌍의 2차원점(x,y) 사이의 거리를 계산하는 함수를 작성하라

[source, scala]
----
def dist(x:(Int, Int), y:(Int, Int)):Double = {
  val yd = y._1 - y._2
  val xd = x._1 - y._2
  math.sqrt(yd * yd + xd * xd)
}
----

자바 루프 for (int i = 10; i >= 0; i++) System.out.println(i); 와 동일한 스칼라 코드를 작성하라.

=== 일급함수

함수??

* 하나 또는 그 이상의 입력 매개변수를 가진다.
* 입력 매개변수만을 가지고 계산을 수행한다.
* 값을 반환하다.
* 동일 입력에 대해 항상 같은 값을 반환한다.
* 함수 외부의 어떤 데이터도 사용하거나 영향을 주지 않는다.
* 함수 외부 데이터에 영향받지 않는다.

일급함수

* 함수가 다른 데이터 타입처럼 사용될 수 있다는 의미
* 다른 함수를 매개변수로 받아들이거나 반환값으로 함수를 사용하는 함수를 고차함수라고 한다.

아래와 같이 함수 타입이 정의된다.

`[<타입>, ...] => <타입>`


[source, scala]
----
def double(x:Int):Int = x * 2
// double: (x: Int)Int

val myDouble:Int => Int = double
// myDouble: Int => Int = $$Lambda$1132/801961118@7abcc0da

myDouble(5)
// Int = 10

val newDouble = double(_)
// newDouble: Int => Int = $$Lambda$1153/207366788@42a89cef

val newMyDouble = double _
// newMyDouble: Int => Int = $$Lambda$1153/207366788@42a89cef
----

고차함수

함수를 인자로 넘겨 사용할 수 있다.

[source, scala]
----
def safeStringOp(s: String, f: String => String) ={
  if(s!=null) f(s) else s
}
// safeStringOp: (s: String, f: String => String)String

def reverser(s : String) = s.reverse
// reverser: (s: String)String

safeStringOp(null, reverser)
// String = null

safeStringOp("Ready", reverser)
// String = ydaeR
----

함수 리터럴

익명함수를 값이나 변수에 할당할 수 있다.

`([<식별자>:<타입>, ....])=>표현식`

[source, scala]
----
val double = (x:Int) => x * 2
// double: Int => Int = $$Lambda$1182/2101744720@75ee63f2

double(2)
// Int = 4
----

위의 safeStringOp는 함수 리터럴을 사용할 경우 다음과 같이 간결하게 사용할 수 있다.

[source, scala]
----
def safeStringOp(s: String, f: String => String) ={
  if(s!=null) f(s) else s
}
// safeStringOp: (s: String, f: String => String)String

safeStringOp("Ready", (r:String)=>r.reverse)
// String = ydaeR
----

자리표시자`_`를 이용하면 함수리터럴을 좀 더 드라마틱하게 줄일 수 있다. 여기서 _는 매개변수의 순서대로 값이 매핑된다.

[source, scala]
----
safeStringOp("Ready", _.reverse)
// String = ydaeR

def op(f:(Int,Int)=>Int) = f(3,5)
op: (f: (Int, Int) => Int)Int

op(_ * _)
// Int = 15
----
