= 스트림 소개

== 스트림 개요

자바7이하의 스타일로 리스트를 조작하는 작업을 할 경우, 다음과 같이 코드를 작성할 수 있다.

[source, java]
----
List<Dish> lowCaloricDishes = new ArrayList<>();

// 칼로리가 400이하인 메뉴만 가지고 온다.
for (Dish d : menu) {
    if (d.getCalories() < 400) {
        lowCaloricDishes.add(d);
    }
}

// 칼로리 순으로 정렬한다
Collections.sort(lowCaloricDishes, new Comparator<Dish>() {
    @Override
    public int compare(Dish o1, Dish o2) {
        return Integer.compare(o1.getCalories(), o2.getCalories());
    }
});

// 요리 이름만 가지고 온다.
List<String> lowCaloricDishesName = new ArrayList<>();
for(Dish d : lowCaloricDishes){
    lowCaloricDishesName.add(d.getName());
}

----

자바8에서 추가된 stream API와 람다 표현식을 사용한다면 다음과 같이 위의 코드를 보다 간결하게 표현할 수 있다.

[source, java]
----
List<String> lowCaloricDishesName = menu
        .stream()
        .filter(d->d.getCalories() < 400)
        .sorted(comparing(Dish::getCalories))
        .map(Dish::getName)
        .collect(toList());
----

Stream API를 사용함으로써 우리는 다음과 같은 장점을 얻을 수 있을 것이다.

====== 선언형 프로그래밍

루프와 if조건문등 제어블록을 사용해서 어떻게 동작을 구현할지 지정할 필요 없이 '저칼로리의 요리만 선택하라'같은 동작의 수행을 지정할 수 있다. 앞서 이야기했었던 동작 파라미터화를 사용한다면 변화하는 요구사항에 더 쉽게 대응할 수 있다.

====== 조립할 수 있음

자바에서는 스트림을 제어할 수 있는 다양한 기본함수들을 제공하고 있다. 이를 조립함으로써 다양한 기능을 유연하게 변경할 수 있다. 예를 들어 위의 식에서 상위 3개의 값만 가져와야 할 경우 `limit(3)`를 끼워넣기만 하면 된다.

====== 병렬화

위의 코드에서 stream을 parallelStream() 으로만 변경하기만 하면, 멀티스레드를 활용한 컬렉션 조작을 할 수 있다.

[source, java]
----
List<String> lowCaloricDishesName = menu
        .parallelStream()
        .filter(d->d.getCalories() < 400)
        .sorted(comparing(Dish::getCalories))
        .map(Dish::getName)
        .collect(toList());
----

나머지 부분은 변경하지 않아도 된다는것에 주목하여야 하며, 스레드를 사용할 때 동시성제어나 경쟁상태등은 stream API가 알아서 처리한다.

== 스트림 시작하기

=== 스트림의 특성

====== 연속된 요소

컬렉션과 마찬가지로 스트림은 특정 요소 형식으로 이루어진 연속된 값 집합의 인터페이스를 제공한다. 컬렉션의 경우 자료를 어떻게 저장할 것인가에 집중한다면 스트림의 경우 map, filter와 같은 표현 계산식이 주를 이룬다.

====== 소스

스트림은 컬렉션, 배열, I/O 자원등의 데이터 제공 소스로부터 데이터를 소비한다.

====== 데이터 처리 연산

스트림은 함수형 프로그래밍 언어에서 일반적으로 지원하는 연산과 데이터베이스와 비슷한 연산을 지원한다. filter, map, reduce, find, match등으로 데이터를 조작할 수 있다. 스트림연산은 순차적으로 또는 병렬로 실행할 수 있다.

====== 파이프라이닝

스트림연산은 다른 스트림연산끼리 연결해서 커다란 파이프라인을 구성할 수 있도록 스트림 자신을 반영한다. 그 덕분에 Lazyness, Short-circuting 같은 최적화도 얻어낼 수 있다.

====== 내부반복

반복자를 통해서 명시적으로 외부에서 반복하는 컬렉션과는 달리 스트림은 내부 반복을 지원한다. 해당 내용은 나중에 조금 더 자세히 이야기해보도록 하자.

=== 스트림 코드 분석

아래의 예제를 통해서 스트림API에 대해서 조금더 살펴보도록 하자.

[source, java]
----
List<String> threeHighCaloricDishesName = menu
        .stream() // <1>
        .filter(d->d.getCalories() > 300) // <2>
        .sorted(comparing(Dish::getCalories)) // <3>
        .map(Dish::getName) // <4>
        .limit(3) // <5>
        .collect(toList()); // <6>
----
<1> menu에서 스트림을 얻는다. 데이터 소스는 menu이며 연속된 요소를 스트림에 제공한다.
<2> filter는 람다를 인수로 받아 스트림에서 특정요소를 제외시킨다. 예제에서는 300칼로리 이상의 요리를 선택한다.
<3> sorted는 입력되는 Comparator를 받아 사용하면 스트림을 정렬할 수 있다. 예제에서는 칼로리를 기준으로 요리를 정렬하였다.
<4> map을 사용하면 한요소를 다른 요소로 변환하거나 정보를 추출할 수 있다. 예제에서는 각각의 요리명을 추출한다.
<5> limit는 정해진 개수 이상의 요소가 스트림에 저장되지 않도록 스트림의 크기를 축소한다.
<6> collect는 스트림을 다른형식으로 변환한다. 예제에서는 스트림을 리스트로 변환했다. 해당 내용은 다음 자료에서 좀 더 자세히 다룬다.

== 스트림과 컬렉션

기존 컬렉션과는 달리 스트림은 연속된 요소형식의 값을 저장하는 자료구조의 인터페이스를 제공한다. 여기서 연속죈이라는 표현은 순차적으로 값에 접근한다는 것을 의미한다.

컬렉션은 현재 자료구조가 포함되는 모든 값을 메모리에 저장하는 자료구조이다. 반면 스트림은 이론적으로 요청할때만 요소를 계산하는 고정된 자료구조이다. 다시 이야기하자면 사용자가 데이터를 요청할때에만 값을 계산하는 게으른 컬렉션이라고 생각하면 좋다.

====== 딱 한번만 탐색할 수 있다.

한번 탐색된 요소를 다시 탐색하기 위해서는 초기 데이터소스에서 새로운 스트림을 만들어야 한다.

[source, java]
----
List<String> title = Arrays.asList("Java8", "In", "Action");

Stream<String> s = title.stream();
//title의 각 단어가 출력된다.
s.forEach(System.out::println);
//IllegalStateException이 발생된다. 스트림이 이미 소비되었거나 닫혔기 때문이다.
s.forEach(System.out::println);
----

====== 외부반복과 내부 반복

컬렉션 인터페이스를 사용할 경우 사용자가 직접 요소를 반복해야 한다.(예를 들어서 for-each문) 반면 스트림 라이브러리는 반복을 내부에서 알아서 처리해주는 내부반복을 사용한다. 함수에 어떤작업이 수행할지만 지정하면 모든 것이 알아서 처리된다.

[source, java]
----
List<String> names = new ArrayList<>();
for(Dish d : menu){
    names.add(d.getName());
}
----

컬렉션 내부의 요소들은 for-each문을 사용하여 직접 가져올 수 있다.

[source, java]
----
List<String> namesWithStream
        = menu.stream().map(Dish::getName).collect(toList());
----

stream을 사용한다면 비단 단순함에 더해서 
